# Basic
name:               "Appehög AB"
title:               "Appehög AB"

author:
  github:           korla
  email:            bengtsson.johannes@gmail.com

copyright:
  year:             2018
  name:             "Johannes Bengtsson"

# Data
demos:
  -
    name: HexGame
    link: https://korla.github.io/hexgame/build/
    source: https://github.com/Korla/hexgame/
    url: /demos/hexgame/
    description: I helped out a little with an open source redux-based game engine called boardgame.io. This is my version of a game called The Hive implemented using that framework.
  -
    name: Raycing
    link: https://korla.github.io/raycing/cordova/www/
    source: https://github.com/oskar/raycing/
    url: /demos/raycing/
    description: A turn-based racing game. Implemented in Three.js, and Vue.js. Builds into an iOS app using Cordova.

# URL
url:                "https://appehog.se"

timezone:           Europe/Stockholm
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]