# Basic
name:               "Appehög AB"

author:
  github:           korla
  email:            bengtsson.johannes@gmail.com

copyright:
  year:             2018
  name:             "Johannes Bengtsson"

# URL
url:                "https://appehog.se"

timezone:           Europe/Stockholm
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]